### ISSUE TITLE
"Terms" page is 404 dead link

### ISSUE THREAD

**Issue by eighthave** [zom/zom.github.io#6]
https://zom.im/terms

Its linked at the bottom of the page:  "Be sure to read Terms and Privacy Policy."

Also, the privacy policy has a number of mentions of chatsecure:
https://zom.im/privacy/

**Comment by eighthave** [comment]
The [README](https://github.com/zom/Zom-Android/blob/master/README.md) also mentions ChatSecure and not Zom.

**Comment by strixaluco** [comment]
I confirm 404 for the [Terms](https://zom.im/terms) page and two issues on the [https://zom.im/privacy/](Privacy policy) page:
1. The title of the page says "ChatSecure together… right now!"
2. There is a mention of chatsecure.org in the _Analytics & Social Sharing Widgets_ section of the text.
