### ISSUE TITLE
what is zombot? is it you or is it spam?

### ISSUE THREAD

**Issue by mailinglists35** [zom/zom.github.io#9]
![img_7708](https://user-images.githubusercontent.com/2054302/33622761-c52e5896-d9ff-11e7-82b9-ddb51e6f1e0a.PNG)

**Comment by mailinglists35** [comment]
I received a notification then when opened the app I see the above screen

**Comment by n8fr8** [comment]
Zombot is a built-in chatbot service that will be launching soon. It was active in the past, but has gone dormant. Apologies for the confusion. It is not spam, but you can delete it if you like.
